#!/usr/bin/env python3
"""
Summarize a locally generated matched canonical/alternate rescore table.

The paired prediction table is a generated experimental artifact and is not
distributed in this repository.

This utility independently recomputes:

1. Canonical and alternate matched accuracy.
2. Available and sequence strata.
3. Exact-lookup accuracy.
4. Discordant-pair counts.
5. Nesting of alternate-correct cases within canonical-correct cases.
6. The exact two-sided McNemar test.

This script verifies the paired-rescore output. It does not recreate the
separate upstream 228-item canonical probability reconstruction gate.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path


REQUIRED = {
    "canonical_task_id",
    "alternate_task_id",
    "y",
    "sequence_label",
    "canonical_correct",
    "alternate_correct",
    "canonical_lookup_correct",
    "alternate_lookup_correct",
}


def parse_args():
    root = Path(__file__).resolve().parents[2]

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--paired-predictions",
        type=Path,
        required=True,
        help=(
            "Local paired prediction CSV generated by "
            "the deterministic reconstruction/rescore."
        ),
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=(
            root
            / "artifacts/audits/"
              "paired_rescore_summary.json"
        ),
    )

    return parser.parse_args()


def exact_two_sided_mcnemar(
    b: int,
    c: int,
) -> float:
    n = b + c

    if n == 0:
        return 1.0

    k = min(
        b,
        c,
    )

    lower_tail = (
        sum(
            math.comb(
                n,
                i,
            )
            for i in range(
                k + 1
            )
        )
        /
        (2 ** n)
    )

    return min(
        1.0,
        2.0 * lower_tail,
    )


def as_int(
    row,
    key,
):
    return int(
        float(
            row[key]
        )
    )


def main():
    args = parse_args()

    with args.paired_predictions.open(
        newline="",
        encoding="utf-8",
    ) as handle:

        reader = csv.DictReader(
            handle
        )

        missing = sorted(
            REQUIRED
            - set(
                reader.fieldnames
                or []
            )
        )

        if missing:
            raise SystemExit(
                f"Missing required columns: {missing}"
            )

        rows = list(
            reader
        )

    n = len(
        rows
    )

    canonical_correct = sum(
        as_int(
            row,
            "canonical_correct",
        )
        for row in rows
    )

    alternate_correct = sum(
        as_int(
            row,
            "alternate_correct",
        )
        for row in rows
    )

    available_rows = [
        row
        for row in rows
        if (
            str(
                row["sequence_label"]
            )
            .strip()
            .lower()
            == "available"
        )
    ]

    sequence_rows = [
        row
        for row in rows
        if (
            str(
                row["sequence_label"]
            )
            .strip()
            .lower()
            != "available"
        )
    ]

    available_canonical = sum(
        as_int(
            row,
            "canonical_correct",
        )
        for row in available_rows
    )

    available_alternate = sum(
        as_int(
            row,
            "alternate_correct",
        )
        for row in available_rows
    )

    sequence_canonical = sum(
        as_int(
            row,
            "canonical_correct",
        )
        for row in sequence_rows
    )

    sequence_alternate = sum(
        as_int(
            row,
            "alternate_correct",
        )
        for row in sequence_rows
    )

    canonical_lookup = sum(
        as_int(
            row,
            "canonical_lookup_correct",
        )
        for row in rows
    )

    alternate_lookup = sum(
        as_int(
            row,
            "alternate_lookup_correct",
        )
        for row in rows
    )

    b = sum(
        (
            as_int(
                row,
                "canonical_correct",
            )
            == 1
        )
        and
        (
            as_int(
                row,
                "alternate_correct",
            )
            == 0
        )
        for row in rows
    )

    c = sum(
        (
            as_int(
                row,
                "canonical_correct",
            )
            == 0
        )
        and
        (
            as_int(
                row,
                "alternate_correct",
            )
            == 1
        )
        for row in rows
    )

    discordant = [
        row
        for row in rows
        if (
            as_int(
                row,
                "canonical_correct",
            )
            !=
            as_int(
                row,
                "alternate_correct",
            )
        )
    ]

    report = {
        "analysis_type":
            "paired canonical/alternate rescore verification",
        "n_paired":
            n,
        "canonical_correct":
            canonical_correct,
        "canonical_accuracy":
            canonical_correct / n
            if n
            else None,
        "alternate_correct":
            alternate_correct,
        "alternate_accuracy":
            alternate_correct / n
            if n
            else None,
        "available_n":
            len(
                available_rows
            ),
        "available_canonical_correct":
            available_canonical,
        "available_alternate_correct":
            available_alternate,
        "sequence_n":
            len(
                sequence_rows
            ),
        "sequence_canonical_correct":
            sequence_canonical,
        "sequence_alternate_correct":
            sequence_alternate,
        "lookup_canonical_correct":
            canonical_lookup,
        "lookup_canonical_accuracy":
            canonical_lookup / n
            if n
            else None,
        "lookup_alternate_correct":
            alternate_lookup,
        "lookup_alternate_accuracy":
            alternate_lookup / n
            if n
            else None,
        "mcnemar_definition_b":
            "canonical correct, alternate wrong",
        "mcnemar_definition_c":
            "canonical wrong, alternate correct",
        "mcnemar_b":
            b,
        "mcnemar_c":
            c,
        "mcnemar_discordant_n":
            b + c,
        "mcnemar_exact_two_sided_p":
            exact_two_sided_mcnemar(
                b,
                c,
            ),
        "alternate_correct_nested_within_canonical_correct":
            c == 0,
        "discordant_pair_count":
            len(
                discordant
            ),
        "note":
            "The separate 228-item canonical reconstruction probability "
            "gate is an upstream verification step and is not recomputed "
            "from this 96-pair table.",
    }

    args.output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    args.output.write_text(
        json.dumps(
            report,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    print(
        json.dumps(
            report,
            indent=2,
        )
    )

    print(
        f"\nWrote: {args.output}"
    )


if __name__ == "__main__":
    main()
